---
name: "Shopping Application AMI Build And Deploy"

on:
  workflow_dispatch:

jobs:
  build-ami:
    name: "Build AMI with Packer"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      PACKER_VERSION: "1.9.4"
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4

      - name: "Set Up Packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: "Initialize Packer"
        run: packer init .
        working-directory: ./packer/

      - name: "Validate Packer Templates"
        run: packer validate .
        working-directory: ./packer/

      - name: "Build AMI Image"
        run: packer build .
        working-directory: ./packer/

  deploy-infra:
    name: "Deploy Infrastructure with Terraform"
    runs-on: ubuntu-latest
    needs: build-ami
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      TERRAFORM_VERSION: "1.12.2"
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4

      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform init
        run: terraform init 
        working-directory: ./terraform/

      - name: Terraform fmt
        run: terraform fmt
        working-directory: ./terraform/

      - name: Terraform validate
        run: terraform validate
        working-directory: ./terraform/

      - name: Terraform plan
        run: terraform plan 
        working-directory: ./terraform/

      - name: Terraform apply
        run: terraform apply -auto-approve 
        working-directory: ./terraform/

